version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - gomoddirectives
    - interfacebloat
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5 # linter complaining too much about missing empty lines.
  settings:
    cyclop:
      max-complexity: 13
    nestif:
      min-complexity: 8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        source: ^func Test
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
