on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go-wasi.yml@cb97cbbcea106d12503c4b329f418cc406cb414a # v4.4.4

  release:
    needs: test
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-go-wasi.yml@cb97cbbcea106d12503c4b329f418cc406cb414a # v4.4.4
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/tests/go-wasi-context-aware-test-policy
